services:

  seismicview:
    volumes:
      - ./src:/src
      - ./tests:/tests
    environment:
      - CONFIG=dev
    networks:
      - ew-proxy

networks:
  ew-proxy:
    external: true
    name: earthworm
