version: "3"

services:

  ew-viewer-ws:
    build:
      context: ./services/stations
      dockerfile: DockerFile.prod
    image: ew-viewer-ws-prod:latest
    container_name: earthworm-websocket-server-prod
    entrypoint: [
        "python",
        "/src/seismicview/main.py"
    ]
    healthcheck:
      # Check that both ports are listening
      test: [ "CMD-SHELL",
              "netstat -tln | grep 13345 && netstat -tln | grep 13342 || exit 1" ]
      interval: 2m
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - CONFIG=prod
      # Address from which the server receives information
      - SERVER_HOST_IP=ew-viewer-ws
      - SERVER_HOST_PORT=13342
      # Address of the websocket server
      - WS_SERVER_HOST_IP=ew-viewer-ws
      - WS_SERVER_HOST_PORT=13345
    ports:
      - "13342:13342"
      - "13345:13345"

  ew-viewer-client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.prod
    image: ew-viewer-client-prod:latest
    container_name: earthworm-viewer-client-dev
    ports:
      - "80:80"

  ew-viewer-auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    image: ew-viewer-auth-prod:latest
    container_name: earthworm-viewer-auth-prod
    env_file:
      - ./services/auth/.env
    restart: unless-stopped
    command: >
      sh -c "
        flask db upgrade &&
        gunicorn --bind 0.0.0.0:5000 ewauth.wsgi:app"
    environment:
      - FLASK_APP=ewauth/app.py
      - DOMAIN_NAME=https://racm-monitor.cires-ac.net
      - CONFIG=prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 3m
      timeout: 10s
      retries: 3
    volumes:
      - db_volume:/db/
    ports:
      - "5000:80"


volumes:
  db_volume:
