version: "3"

services:

  ew-viewer-ws:
    build:
      context: ./services/stations
      dockerfile: DockerFile
    image: ew-viewer-ws-dev:latest
    container_name: earthworm-websocket-server-dev
    entrypoint: [
        "python",
        "/src/seismicview/main.py"
    ]
    healthcheck:
      # Check that both ports are listening
      test: [ "CMD-SHELL",
              "netstat -tln | grep 13345 && netstat -tln | grep 13342 || exit 1" ]
      interval: 2m
      timeout: 10s
      retries: 3
    environment:
      - CONFIG=dev
      # Address from which the server receives information
      - SERVER_HOST_IP=ew-viewer-ws
      - SERVER_HOST_PORT=13342
      # Address of the websocket server
      - WS_SERVER_HOST_IP=ew-viewer-ws
      - WS_SERVER_HOST_PORT=13345
    ports:
      - "13342:13342"
      - "13345:13345"
    volumes:
      - ./services/stations/src:/src
      - ./services/stations/tests:/tests
