version: "3"

services:

  seismicview:
    build:
      context: .
      dockerfile: DockerFile
    image: ew-seismicview:latest
    container_name: earthworm-websocket-server
    entrypoint: [
        "python",
        "/src/seismicview/main.py"
    ]
    environment:
      # Address from which the server receives information
      - SERVER_HOST_IP=seismicview
      - SERVER_HOST_PORT=13342
      # Address of the websocket server
      - WS_SERVER_HOST_IP=seismicview
      - WS_SERVER_HOST_PORT=13345
    networks:
      - ew-proxy
    ports:
      - "13342:13342"
      - "13345:13345"

networks:
  ew-proxy:
    external: true
    name: earthworm