# base
FROM python:3.11-alpine as base

COPY pyproject.toml /pyproject.toml
COPY requirements /requirements/
COPY src/ /src/
COPY tests/ /tests/

RUN mkdir -p /logs && \
    pip install -r /requirements/dev.txt \

