version: "3"

services:

  ew-viewer-ws:
    build:
      context: ./services/stations
      dockerfile: DockerFile
    image: ew-viewer-ws-dev:latest
    container_name: earthworm-websocket-server-dev
    entrypoint: [
        "python",
        "/src/seismicview/main.py"
    ]
    healthcheck:
      # Check that both ports are listening
      test: [ "CMD-SHELL",
              "netstat -tln | grep 13345 && netstat -tln | grep 13342 || exit 1" ]
      interval: 2m
      timeout: 10s
      retries: 3
    environment:
      - CONFIG=dev
      # Address from which the server receives information
      - SERVER_HOST_IP=ew-viewer-ws
      - SERVER_HOST_PORT=13342
      # Address of the websocket server
      - WS_SERVER_HOST_IP=ew-viewer-ws
      - WS_SERVER_HOST_PORT=13345
      # Domain for unit testing
      - HOST_DOMAIN_TEST=0.0.0.0
    ports:
      - "13342:13342"
      - "13345:13345"
    volumes:
      - ./services/stations/src:/src
      - ./services/stations/tests:/tests

  ew-viewer-client:
    stdin_open: true
    build:
      context: ./services/client
      dockerfile: Dockerfile
    image: ew-viewer-client-dev:latest
    container_name: earthworm-viewer-client-dev
    volumes:
      - ./services/client/src:/app/src
#      - ./services/client/node_modules:/app/node_modules
      - ./services/client/vite.config.js:/app/vite.config.js
    ports:
      - "5173:5173"
    env_file:
      - services/client/.env

  ew-viewer-auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    image: ew-viewer-auth-dev:latest
    container_name: earthworm-viewer-auth-dev
    env_file:
      - ./services/auth/.env
    command: >
      sh -c "
        flask wait-for-db &&
        flask db upgrade &&
        flask insert-admin &&
        flask run --host=0.0.0.0 --port=80"
    environment:
      - FLASK_APP=ewauth/app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres
      - DB_USER=ewauth
      - DB_NAME=ewauth
      - DB_PASSWORD=abc123
      - DB_PORT=5432
      - API_HOST=ew-viewer-auth
      - CONFIG=dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
    volumes:
      - ./services/auth/src:/src
      - ./services/auth/tests:/tests
    ports:
      - "5000:80"

  postgres:
    image: postgres:15.2-alpine
    container_name: ew-auth-db
    environment:
      # Note user and db name will be the same
      - POSTGRES_USER=ewauth
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"

  wave-client:
    build:
      context: ./services/stations
      dockerfile: DockerFile
    image: ew-viewer-ws-dev:latest
    container_name: wave-client-dev
    entrypoint: [
      "python",
      "/src/seismicview/test/client.py"
    ]
    environment:
      - CONFIG=dev
      # Address from which the server receives information
      - SERVER_HOST_IP=ew-viewer-ws
      - SERVER_HOST_PORT=13342
    volumes:
      - ./services/stations/src:/src