# BUILDER #

FROM node:19-alpine as builder

WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json .
COPY package-lock.json .
RUN npm ci

COPY . .
RUN npm run build

# Nginx #

FROM nginx:stable-alpine

RUN rm -rf /etc/nginx/conf.d
RUN mkdir "/etc/nginx/conf.d/"
COPY nginx/http.conf /etc/nginx/conf.d/default.conf

# copy static files
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80
