name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  test-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build container
      run: docker compose up ew-viewer-ws -d

    - name: Run tests
      run: docker compose run --rm --no-deps --entrypoint=pytest ew-viewer-ws /tests/

  test-client:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker compose up ew-viewer-client -d

      - name: Run tests
        run: docker compose run --rm --no-deps --entrypoint="npm run test-ci" ew-viewer-client

  test-auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker compose up ew-viewer-client -d

      - name: Run tests
        run: docker compose run --rm --no-deps --entrypoint=pytest ew-viewer-auth /tests/